version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    file_exists_behavior: OVERWRITE   # ← This will overwrite all files safely
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/reload.sh   # ← Graceful reload = zero downtime
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
