version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
